apiVersion: v1
kind: Pod
metadata:
  name: jobgenerator
  labels:
    name: jobgenerator
spec:
  serviceAccountName: kube-client
  restartPolicy: Never
  containers:
    - name: generator
      image: 0gis0/kubenodejs
      imagePullPolicy: Always
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
